### ISSUE TITLE
dopar, and else

### ISSUE THREAD

**Issue by jiw181** [ZxZhou4150/Redeconve#7]
Hello,

Thank you for developing this package, which runs pretty fast. :-)

Here are some questions about this package:
1. we run into an error for dopar=T: # Error in Rmpi::mpi.comm.spawn(slave = mpitask, slavearg = args, nslaves = count, MPI_ERR_SPAWN: could not spawn processes.  What might be the reason and how to solve this error?
2. If we want to get cell type proportions, should we generate the matrix for cell types then deconvulute to cell type proportion directly, or should we deconvolute to cell states first then sum for cell type proportion?
3. We had samples that were sequenced on different days. It looks like there are some batch effects between libraries. How should we do a batch correct for the cell state/type proportion before any down stream analysis, eg. co-localization?
4. How should we pronounce the package name, is it /'redi'convi/, /ri'diconv/, or something else?

Thanks

**Comment by ZxZhou4150** [comment]
Hi,

Thanks for your recognition for our package! Here are my answers or suggestions:

1. This issue is pretty local and is probably caused by the package `snow`. I'm really not an expert on it but I have some links for your reference:
[1:https://stackoverflow.com/questions/46541301/new-install-dompi-throwing-mpi-err-spawn-error](https://stackoverflow.com/questions/46541301/new-install-dompi-throwing-mpi-err-spawn-error)
[2:https://stackoverflow.com/questions/19066606/r-error-in-rmpi-with-snow](https://stackoverflow.com/questions/19066606/r-error-in-rmpi-with-snow)
2. Please refer to #6 for a detailed explanation of the difference between these two conditions. Overall, we suggest deconvoluting first then sum up.
3. Is it sc or st data that you are having the batch effect? It doesn't matter if it's st, for we handle each st slide separately. If it's sc, sorry but we do not offer a batch effect correction method. You can first use some well-developed packages, e.g., Seurat or Harmony, to remove the batch effect, and then do deconvolution.
4. There is no official way of pronouncing it😂 We usually pronounce it as /redi'conv/.

Hope my answers can help you. Feel free to ask if you have further questions!

Zixiang
